// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'Fun_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhPnMDW5RCcNKHjw2NQYZpPu11YunEfCo',
    appId: '1:531801865008:ios:ef54ad656852f72200a6f5',
    messagingSenderId: '531801865008',
    projectId: 'gps-coordinate-6dbab',
    storageBucket: 'gps-coordinate-6dbab.firebasestorage.app',
    iosBundleId: 'ds.ahmdemotestapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBNeNZjO-vufnAov_9UnSlP6NBSezMiims",
    // appId: "1:805084640337:android:eed59ec1ba76bcd30b3470",
       appId: "1:805084640337:android:eed59ec1ba76bcd30b3470",
    messagingSenderId: "805084640337",
    projectId: "promptly-4e3e6",
    storageBucket: 'promptly-4e3e6.firebasestorage.app',
  );
}
