name: Android Deploy

on:
  workflow_dispatch:
    inputs:
      track:
        description: "Deployment Track"
        required: true
        default: "internal"
        type: choice
        options:
          - internal
          - production

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ github.event.inputs.track }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks

      - name: Create Play Store Key
        run: |
          echo '${{ secrets.PLAY_STORE_JSON_KEY }}' > android/play-store-key.json

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        working-directory: android
        run: bundle install

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build App Bundle
        run: flutter build appbundle --release --no-tree-shake-icons
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Deploy with Fastlane
        working-directory: android
        env:
          PLAY_STORE_JSON_PATH: play-store-key.json
        run: bundle exec fastlane ${{ github.event.inputs.track }}